DELETE http://localhost:3001/message/61637a52b0ce40a3fb31232c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNjIzZmE5MjY2OWU2NjU3Nzc5M2NjYSIsInVzZXJuYW1lIjoiY2FyZXNsZTEyMyIsImlhdCI6MTYzMzkwODcyMX0.xu0yZakS1NhVm4mZSD8lmI8D1CyAkPL0ZEnWJDYLc2